const lang = [  ﻿`ماذا؟ لا أحب الرسائل الفارغة.`,
                `Wat? Ek hou nie van leë boodskappe nie.`,
                `Çfarë? Nuk më pëlqen mesazhet e zbrazëta.`,
                `ምንድን? ባዶ መልእክቶችን አልወድም.`,
                `Ինչ? Ես չգիտեմ դատարկ հաղորդագրությունները:`,
                `Nə? Boş mesajlar sevmirəm.`,
                `Zer? Ez zait gustatzen mezu hutsak.`,
                `Што? Я не люблю пустыя паведамленні.`,
                `কি? আমি খালি বার্তা পছন্দ করি না`,
                `Šta? Ne volim prazne poruke.`,
                `Какво? Не ми харесват празни съобщения.`,
                `Què? No m'agraden els missatges buits.`,
                `Unsa? Dili ko gusto ang mga mensahe nga walay sulod.`,
                `Chani? Sindimakonda mauthenga opanda kanthu.`,
                `什么？ 我不喜欢空消息。`,
                `Chi? Ùn vogliu micca messi bianchi.`,
                `Što? Ne sviđa mi se praznih poruka.`,
                `Co? Nemám rád prázdné zprávy.`,
                `Hvad? Jeg kan ikke lide tomme beskeder.`,
                `Wat? Ik hou niet van lege berichten.`,
                `Kio? Mi ne ŝatas malplenajn mesaĝojn.`,
                `Mida? Mulle ei meeldi tühjad sõnumid.`,
                `Ano? Hindi ko gusto ang mga walang laman na mensahe.`,
                `Mitä? En pidä tyhjiä viestejä.`,
                `Quelle? Je n'aime pas les messages vides.`,
                `Wat? Ik fiel gjin lege berjochten.`,
                `Que? Non me gustan as mensaxes baleiras.`,
                `რა? მე არ მომწონს ცარიელი შეტყობინებები.`,
                `Was? Ich mag keine leeren Nachrichten.`,
                `Τι? Δεν μου αρέσουν κενά μηνύματα.`,
                `શું? મને ખાલી સંદેશાઓ પસંદ નથી`,
                `Kisa? Mwen pa renmen mesaj vid.`,
                `Menene? Ba na son saƙonnin banza.`,
                `He aha? ʻAʻole wau makemake i nā leka nele.`,
                `מה? אני לא אוהב הודעות ריקות.`,
                `क्या? मुझे खाली संदेश पसंद नहीं हैं।`,
                `Dab tsi? Kuv tsis nyiam npliag lus.`,
                `Mit? Nem szeretem az üres üzeneteket.`,
                `Hvað? Mér líkar ekki við tóm skilaboð.`,
                `Kedu? Ozighị efu ozi m anaghị amasị m.`,
                `Apa? Saya tidak suka pesan kosong.`,
                `Cad? Ní maith liom teachtaireachtaí folamh.`,
                `Che cosa? Non mi piacciono i messaggi vuoti.`,
                `何？ 私は空のメッセージが好きではありません。`,
                `Apa? Aku ora seneng pesen kosong.`,
                `ಏನು? ನನಗೆ ಖಾಲಿ ಸಂದೇಶಗಳು ಇಷ್ಟವಿಲ್ಲ.`,
                `Не? Бос хабарларды ұнатпаймын.`,
                `តើអ្វីទៅ? ខ្ញុំមិនចូលចិត្តសារទទេ។`,
                `뭐? 나는 빈 메시지를 좋아하지 않는다.`,
                `Çi? Ez naxwazin peyamên vala ne.`,
                `Эмне? Мен куру билдирүүлөрдү жакпайт.`,
                `ແມ່ນ​ຫຍັງ? ຂ້ອຍບໍ່ມັກຂໍ້ຄວາມທີ່ເປົ່າຫວ່າງ.`,
                `Quid est? Non ut vacua dispenses.`,
                `Kas? Man nepatīk tukšas ziņas.`,
                `Ką? Man nepatinka tušti pranešimai.`,
                `Waat? Ech hu gär Loscht ze läschen.`,
                `Што? Не ми се допаѓа празни пораки.`,
                `Inona? Tsy tiako ny hafatra tsy misy.`,
                `Apa? Saya tidak suka mesej kosong.`,
                `എന്ത്? എനിക്ക് ശൂന്യമായ സന്ദേശങ്ങൾ ഇഷ്ടമല്ല.`,
                `Xiex? M'għandix bħal messaġġi vojta.`,
                `He aha? Kare au e pai ana ki nga karere kore.`,
                `काय? मला रिक्त संदेश आवडत नाहीत.`,
                `Юу вэ? Би хоосон зурвасуудад дургүй.`,
                `ဘာ? ငါအချည်းနှီးသောမက်ဆေ့ခ်ျကိုကြိုက်ကြဘူး။`,
                `के? मलाई खाली सन्देशहरू मनपर्दैन।`,
                `Hva? Jeg liker ikke tomme meldinger.`,
                `څه؟ زه خالي پیغامونه نه خوښوم.`,
                `چی؟ پیام های خالی را دوست ندارم`,
                `Co? Nie lubię pustych wiadomości.`,
                `O que? Eu não gosto de mensagens vazias.`,
                `ਕੀ? ਮੈਨੂੰ ਖਾਲੀ ਸੰਦੇਸ਼ ਪਸੰਦ ਨਹੀਂ ਹਨ`,
                `Ce? Nu-mi plac mesajele goale.`,
                `Какие? Мне не нравятся пустые сообщения.`,
                `O le a? Ou te le fiafia i savali leai.`,
                `Dè? Cha toil leam teachdaireachdan falamh.`,
                `Шта? Не волим празне поруке.`,
                `Eng? Ha ke rate melaetsa e se nang letho.`,
                `Chii? Handidi mharidzo isina chinhu.`,
                `ڇا؟ آئون خالي پيغام پسند نه ٿو ڪريان.`,
                `Čo? Nemám rád prázdne správy.`,
                `Kaj? Ne maram praznih sporočil.`,
                `Waa maxay? Ma jecli fariimo faaruq ah.`,
                `Naon? Kuring teu resep seratan kosong.`,
                `Nini? Siipendi ujumbe usio na kitu.`,
                `Vad? Jag gillar inte tomma meddelanden.`,
                `Чӣ? Ман паёмҳои холӣ надорам.`,
                `என்ன? எனக்கு வெற்று செய்திகளை பிடிக்கவில்லை.`,
                `ఏం? నాకు ఖాళీ సందేశాలను ఇష్టం లేదు.`,
                `อะไร? ฉันไม่ชอบข้อความว่างเปล่า`,
                `Ne? Boş mesajları sevmiyorum.`,
                `Що? Я не люблю порожні повідомлення.`,
                `کیا؟ مجھے خالی پیغامات پسند نہیں ہیں.`,
                `Nima? Bo'sh xabarlarni yoqtirmayman.`,
                `Gì? Tôi không thích tin nhắn trống.`,
                `Beth? Dwi ddim yn hoffi negeseuon gwag.`,
                `Intoni? Andiyithandi imilayezo engenanto.`,
                `Kini? Emi ko fẹran awọn ifiranṣẹ ofo.`,
                `Ini? Angithandi imilayezo engenalutho.`];

module.exports = lang;
